# 2023-01-30 self attention layers

In [1]:
# download data

In [2]:
import torch
torch.cuda.device_count(), torch.cuda.current_device()

(1, 0)

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [4]:
# !wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [5]:
# read on review data
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [6]:
# Here is all unique character that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)

In [7]:
# create a mapping from characters to integers
ctoi = {c: i for i, c in enumerate(chars)}
itoc = {i: c for i, c in enumerate(chars)}

encode = lambda s: [ctoi[c] for c in s]
decode = lambda l: ''.join([itoc[i] for i in l])

print(encode("hi there"))

print(decode(encode("hi there")))

[46, 47, 1, 58, 46, 43, 56, 43]
hi there


In [8]:
# Let now encode the entire text dataset and store it into torch.Tensor
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)

data[0:100]

torch.Size([1115394]) torch.int64


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])

In [9]:
# Let's now split up the data into train set and validation set
n = round(len(data) * 0.9);
train_data = data[:n]
val_data   = data[n:]
len(train_data), len(val_data)

(1003855, 111539)

In [10]:
block_size = 8
train_data[:block_size]

tensor([18, 47, 56, 57, 58,  1, 15, 47])

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]

for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print(f"when context is {context} the target: {target}.")

when context is tensor([18]) the target: 47.
when context is tensor([18, 47]) the target: 56.
when context is tensor([18, 47, 56]) the target: 57.
when context is tensor([18, 47, 56, 57]) the target: 58.
when context is tensor([18, 47, 56, 57, 58]) the target: 1.
when context is tensor([18, 47, 56, 57, 58,  1]) the target: 15.
when context is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47.
when context is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58.


In [12]:
torch.manual_seed(1337)

batch_size = 4
block_size = 8

def get_batch(split='train'):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(train_data) - block_size, (batch_size, ))
    xb = torch.stack([train_data[i:i+block_size] for i in ix])
    yb = torch.stack([train_data[i+1:i+1+block_size] for i in ix])
    xb, yb = xb.to(device), yb.to(device)
    return xb, yb

xb, yb = get_batch()
print(xb)
print(yb)
for b in range(batch_size):
    for i in range(block_size):
        x = xb[b,:i+1]
        y = yb[b,i]
        print(f"when context is {x} the target: {y}.")

tensor([[56,  6,  0, 24, 43, 58,  1, 61],
        [39, 47, 51,  1, 58, 46, 39, 58],
        [52, 45,  1, 58, 53,  1, 57, 39],
        [43, 47, 52, 45,  1, 46, 53, 50]], device='cuda:0')
tensor([[ 6,  0, 24, 43, 58,  1, 61, 46],
        [47, 51,  1, 58, 46, 39, 58,  1],
        [45,  1, 58, 53,  1, 57, 39, 63],
        [47, 52, 45,  1, 46, 53, 50, 47]], device='cuda:0')
when context is tensor([56], device='cuda:0') the target: 6.
when context is tensor([56,  6], device='cuda:0') the target: 0.
when context is tensor([56,  6,  0], device='cuda:0') the target: 24.
when context is tensor([56,  6,  0, 24], device='cuda:0') the target: 43.
when context is tensor([56,  6,  0, 24, 43], device='cuda:0') the target: 58.
when context is tensor([56,  6,  0, 24, 43, 58], device='cuda:0') the target: 1.
when context is tensor([56,  6,  0, 24, 43, 58,  1], device='cuda:0') the target: 61.
when context is tensor([56,  6,  0, 24, 43, 58,  1, 61], device='cuda:0') the target: 46.
when context is tensor(

In [13]:
print(xb) # input to our transformer

tensor([[56,  6,  0, 24, 43, 58,  1, 61],
        [39, 47, 51,  1, 58, 46, 39, 58],
        [52, 45,  1, 58, 53,  1, 57, 39],
        [43, 47, 52, 45,  1, 46, 53, 50]], device='cuda:0')


In [14]:
# self attention layer

In [15]:
import torch

torch.manual_seed(1338)

B, T, C = 4, 8, 2 ; # batch, time, channel

x = torch.randn((B, T, C))

x[0]

tensor([[-1.3113, -1.0017],
        [-1.2342,  0.1297],
        [-0.5150, -1.2666],
        [-0.6719,  0.1851],
        [ 0.9367,  0.3139],
        [-1.3950,  0.1132],
        [ 0.3622,  2.5192],
        [-0.7672, -0.9529]])

In [16]:
# version 1
xbow = torch.zeros_like(x)
for b in range(B):
    for t in range(T):
        x_prev = x[b, :t+1] # t, C
        xbow[b,t] = torch.mean(x_prev, dim=0)
xbow[0]

tensor([[-1.3113, -1.0017],
        [-1.2728, -0.4360],
        [-1.0202, -0.7129],
        [-0.9331, -0.4884],
        [-0.5591, -0.3279],
        [-0.6985, -0.2544],
        [-0.5469,  0.1418],
        [-0.5745,  0.0050]])

In [17]:
# version 2
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(dim=1, keepdim=True)
xbow2 = wei @ x # (B, T, T) x (B, T, C) -> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [18]:
# version 3
# using solfmax
wei = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(wei==0, -torch.inf)
wei = torch.softmax(wei, dim=-1)
xbow3 = wei @ x # (B, T, T) x (B, T, C) -> (B, T, C)
torch.allclose(xbow, xbow3)

True

In [19]:
import torch
import torch.nn as nn

torch.manual_seed(1337)

B, T, C = 4, 8, 32 ; # batch, time, channel
head_size = 16

x = torch.randn((B, T, C))

query = nn.Linear(C, head_size, bias=False)
key = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

q = query(x) # (B, T, head_size)
k = key(x) # (B, T, head_size)
v = value(x) # (B, T, head_size)

wei = q@k.transpose(-2, -1) # (B, T, head_size) @ (B, head_size, head_size, T) -> (B, T, T)
wei = wei / torch.sqrt(torch.tensor(head_size))
tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril==0, -torch.inf)
wei = torch.softmax(wei, dim=-1)

out = wei @ v # (B, T, T) x (B, T, C) -> (B, T, C)

q.shape, k.shape, v.shape, wei.shape, out.shape

(torch.Size([4, 8, 16]),
 torch.Size([4, 8, 16]),
 torch.Size([4, 8, 16]),
 torch.Size([4, 8, 8]),
 torch.Size([4, 8, 16]))

In [20]:
drop_out = 0.2

In [21]:
# create a class for self attention layer
class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.query = nn.Linear(C, head_size)
        self.key = nn.Linear(C, head_size)
        self.value = nn.Linear(C, head_size)
        self.register_buffer('tril', torch.tril(torch.ones(T, T)))
        self.dropout = nn.Dropout(drop_out)
    def forward(self, x):
        B, T, C = x.shape
        q = self.query(x) # B, T, head_size
        k = self.key(x) # B, T, head_size
        v = self.value(x) # B, T, head_size
        # computer attention score
        wei = q @ v.transpose(-2, -1) * head_size ** -0.5 # (B, T, head_size) x (B, head_size, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = torch.softmax(wei,dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation
        out = wei@v # (B, T, T) x (B, T, head_size) -> (B, T, head_size)
        return out
    
class MultipleHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        n_embd = head_size * num_heads
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(drop_out)
    def forward(self, x):
        out = torch.cat([head(x) for head in self.heads], -1)
        out = self.dropout(self.proj(out))
        return out

class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
                        nn.Linear(n_embd, n_embd * 4),
                        nn.ReLU(),
                        nn.Linear(n_embd * 4, n_embd),
                        nn.Dropout(drop_out)
                    )
    
    def forward(self, x):
        x = self.net(x)
        return x
    
class Block(nn.Module):
    def __init__(self, num_heads, n_embd):
        super().__init__()
        head_size = n_embd//num_heads
        self.sa_head = MultipleHeadAttention(num_heads, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)
    def forward(self, x):
        x = self.sa_head(self.ln1(x)) + x
        x = self.ffwd(self.ln2(x)) + x
        return x

head = Head(2)
out = head(x)
print(out.shape)


multi_heads = MultipleHeadAttention(4, 2)
out = multi_heads(x)
print(out.shape)

ffwd = FeedForward(8)
out = ffwd(out)
print(out.shape)

x = torch.randn((4, 8, 32))
block = Block(4, 32)
out = block(x)
print(out.shape)

blocks = nn.Sequential(*nn.ModuleList([Block(4, 32) for _ in range(4)]))
blocks(x).shape

torch.Size([4, 8, 2])
torch.Size([4, 8, 8])
torch.Size([4, 8, 8])
torch.Size([4, 8, 32])


torch.Size([4, 8, 32])

In [22]:
torch.manual_seed(1338)
x = torch.randn((4, 8, 32))
print(x[0, 0].mean(), x[0, 0].var())

layer_norm = nn.LayerNorm(32)
x = layer_norm(x)
print(x[1, 1].mean(), x[2, 2].var())

tensor(-0.2145) tensor(1.0175)
tensor(-5.5879e-09, grad_fn=<MeanBackward0>) tensor(1.0322, grad_fn=<VarBackward0>)


In [44]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
import numpy as np

torch.manual_seed(1337)

@torch.no_grad()
def estimate_loss():
    model.eval()
    losses = torch.zeros(eval_iters)
    out = {}
    for split in ['train', 'val']:
        for i in range(eval_iters):
            xb, yb = get_batch()
            loss, logits = model(xb, yb)
            losses[i] = loss
        out[split] = losses.mean().item()
    return out

# bigram language model
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(T, n_embd)
        self.blocks = nn.Sequential(*nn.ModuleList([Block(num_heads, n_embd) for _ in range(num_blocks)] + [nn.LayerNorm(n_embd)]))
        self.lm_head = nn.Linear(n_embd, vocab_size)
        
    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T).to(device))
        x = tok_emb + pos_emb # (B, T, n_embd)
        x = self.blocks(x)
        logits = self.lm_head(x) # (B, n_embd, vocab_size) x (B, T, n_embd) -> (B, T, vocab_size)
        if targets is not None:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        else:
            loss = None
        return loss, logits

    @torch.no_grad()
    def generate(self, idx, max_new_token):
        for i in range(max_new_token):
            loss, logits = self(idx[:, -block_size:])
            logits = logits[:, -1,:]
            probs = F.softmax(logits, -1)
            next_idx = torch.multinomial(probs, 1)
            idx = torch.cat([idx, next_idx], 1)
        return idx

def train(lr=0.001):
    optimizer = AdamW(model.parameters())
    for i in range(max_iter):
        if i % eval_iters == 0:
            out = estimate_loss()
            print(f"Train loss: {out['train']}. Val loss: {out['val']}. ")
        xb, yb = get_batch()
        loss, logits = model(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()


B, T, C = 32, 8, 32 ; # batch, time, channel
n_embd = 32
batch_size, block_size = B, T
max_iter = 3000
num_heads = 4
num_blocks = 4
eval_iters = 200
eval_interval = 300
drop_out = 0.2
head_size = 16
lr = 0.001
xb, yb = get_batch()
print(xb.shape, yb.shape)

model = BigramLanguageModel(vocab_size).to(device)
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
loss, logits = model(xb, yb)
print(loss)

torch.Size([32, 8]) torch.Size([32, 8])
0.055361 M parameters
tensor(4.3424, device='cuda:0', grad_fn=<NllLossBackward0>)


In [45]:
train(lr=lr)

sent = model.generate(idx=torch.zeros((1,1), dtype=torch.long).to(device), max_new_token=500)
print(decode(sent[0].tolist()))

Train loss: 4.321711540222168. Val loss: 4.3166890144348145. 
Train loss: 2.628936767578125. Val loss: 2.624739408493042. 
Train loss: 2.4622747898101807. Val loss: 2.44834566116333. 
Train loss: 2.355565309524536. Val loss: 2.368675470352173. 
Train loss: 2.3013672828674316. Val loss: 2.307973861694336. 
Train loss: 2.2792253494262695. Val loss: 2.257150173187256. 
Train loss: 2.213599920272827. Val loss: 2.2309978008270264. 
Train loss: 2.1946682929992676. Val loss: 2.1950509548187256. 
Train loss: 2.173604965209961. Val loss: 2.1605870723724365. 
Train loss: 2.150628089904785. Val loss: 2.1470084190368652. 
Train loss: 2.1047801971435547. Val loss: 2.122055768966675. 
Train loss: 2.1058385372161865. Val loss: 2.1245391368865967. 
Train loss: 2.0994021892547607. Val loss: 2.0904626846313477. 
Train loss: 2.084693431854248. Val loss: 2.06416654586792. 
Train loss: 2.0675899982452393. Val loss: 2.0804712772369385. 

There madire my be dontanth the the gatauss:
Whith fou quith bubard th

In [46]:
train(lr=lr / 10)
    
sent = model.generate(idx=torch.zeros((1,1), dtype=torch.long).to(device), max_new_token=500)
print(decode(sent[0].tolist()))

Train loss: 2.059319496154785. Val loss: 2.068618059158325. 
Train loss: 2.036330461502075. Val loss: 2.0403547286987305. 
Train loss: 2.031339645385742. Val loss: 2.044156551361084. 
Train loss: 2.0190982818603516. Val loss: 2.01851487159729. 
Train loss: 2.018770694732666. Val loss: 2.017512083053589. 
Train loss: 2.0143983364105225. Val loss: 2.0045251846313477. 
Train loss: 2.0146372318267822. Val loss: 2.0047690868377686. 
Train loss: 1.9856127500534058. Val loss: 1.987217664718628. 
Train loss: 2.001513957977295. Val loss: 1.9895679950714111. 
Train loss: 1.9798648357391357. Val loss: 1.9773995876312256. 
Train loss: 1.975059986114502. Val loss: 1.9695318937301636. 
Train loss: 1.9763429164886475. Val loss: 1.9809887409210205. 
Train loss: 1.9702671766281128. Val loss: 1.9717223644256592. 
Train loss: 1.952070951461792. Val loss: 1.961246132850647. 
Train loss: 1.9795931577682495. Val loss: 1.9745793342590332. 

Which hansoung; mysee--'nome.

GLOUCENTER:
Your must her thy well on

In [47]:
# hyperparameters
# batch_size = 16 # how many independent sequences will we process in parallel?
# block_size = 32 # what is the maximum context length for predictions?
# max_iters = 5000
# eval_interval = 100
# learning_rate = 1e-3
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# eval_iters = 200
# n_embd = 64
# n_head = 4
# n_layer = 4
# dropout = 0.0
# ------------


B, T, C = 64, 256, 384 ; # batch, time, channel
n_embd = C
batch_size, block_size = B, T
max_iter = 5000
num_heads = 6
num_blocks = 6
eval_iters = 200
eval_interval = 100
drop_out = 0.2
head_size = n_embd / num_heads
xb, yb = get_batch()
lr = 0.0001
print(xb.shape, yb.shape)

model = BigramLanguageModel(vocab_size).to(device)
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
loss, logits = model(xb, yb)
print(loss)

torch.Size([64, 256]) torch.Size([64, 256])
10.795841 M parameters
tensor(4.3118, device='cuda:0', grad_fn=<NllLossBackward0>)


In [48]:
train(lr=lr)

sent = model.generate(idx=torch.zeros((1,1), dtype=torch.long).to(device), max_new_token=500)
print(decode(sent[0].tolist()))

Train loss: 4.313438415527344. Val loss: 4.313441276550293. 
Train loss: 2.3319079875946045. Val loss: 2.3343961238861084. 
Train loss: 1.7826370000839233. Val loss: 1.7811328172683716. 
Train loss: 1.5002878904342651. Val loss: 1.502394437789917. 
Train loss: 1.3738418817520142. Val loss: 1.3710038661956787. 
Train loss: 1.2927336692810059. Val loss: 1.2913239002227783. 
Train loss: 1.2260199785232544. Val loss: 1.226985216140747. 
Train loss: 1.1693129539489746. Val loss: 1.1708018779754639. 
Train loss: 1.1149369478225708. Val loss: 1.1125400066375732. 
Train loss: 1.060459852218628. Val loss: 1.0564154386520386. 


KeyboardInterrupt: 

### Convert this file to md

In [29]:
from IPython.core.display import Javascript

In [30]:
%%js
IPython.notebook.kernel.execute('this_notebook = "' + IPython.notebook.notebook_name + '"')

<IPython.core.display.Javascript object>

In [31]:
this_notebook

NameError: name 'this_notebook' is not defined

In [ ]:
!jupyter nbconvert --to markdown {this_notebook} --output-dir=../_posts